### ISSUE TITLE
Use scribble.png get bad result

### ISSUE THREAD

**Issue by lfxx** [pymatting/pymatting#10]
i use scribble.png instead of trimap to compute alpha,the result is not good
![lemur](https://user-images.githubusercontent.com/27956643/75991538-91a88c80-5f31-11ea-9f68-e0f8bff44b45.png)
![lemur_caotu](https://user-images.githubusercontent.com/27956643/75991551-966d4080-5f31-11ea-8748-089734e7806d.png)
![lemur_alpha](https://user-images.githubusercontent.com/27956643/75991735-e0562680-5f31-11ea-82e4-7f5aebdf02c1.png)
 what wrong with this?hope for your kindly reply@99991

**Comment by 99991** [comment]
Unfortunately, scribbles are not supported. The reason is that it is impossible to tell if a pixel is black because it is a scribble or because the image is black. It is pure coincidence that it works this well at all.

When converting the scribbles to a trimap, you can see that there is a black pixel in the trimap because the lemur has a black pixel.

![trimap_error](https://user-images.githubusercontent.com/18725165/76062154-66e82380-5f85-11ea-8bc0-5307843c02f6.png)

```Python3
from pymatting import *

# convert scribbles to trimap

scribbles = load_image("scribbles.png", "GRAY")

is_fg = scribbles == 1.0
is_bg = scribbles == 0.0

trimap = 0.5 + 0.5 * is_fg - 0.5 * is_bg

save_image("trimap.png", trimap)
```

Removing the stray black pixel in the trimap will produce this alpha matte, where the black part of the lemur is correct now:

![alpha](https://user-images.githubusercontent.com/18725165/76062563-3ce33100-5f86-11ea-8b9a-236f9c26b781.png)

In addition, you could use knn alpha matting to get rid of most of the errors around the lemur, but it does not work well for the eyes because their color is substantially different from the colors which are constrained with the trimap.

![alpha](https://user-images.githubusercontent.com/18725165/76064635-5d14ef00-5f8a-11ea-918a-c2a4c52ba905.png)

```Python3
from pymatting import *

image = load_image("image.png", "RGB")
trimap = load_image("trimap.png", "GRAY")

alpha = estimate_alpha_knn(image, trimap, laplacian_kwargs=dict(
    n_neighbors=[10,10],
    distance_weights=[10.0, 0.01],
))

save_image("alpha.png", alpha)
```

But I'm afraid that you will need a better trimap to get perfect results.

**Comment by lfxx** [comment]
Much thanks for your specific reply,looks like that just use scribbles is not enough to get perfect result.Is it exist which the work can perform well on scribbles?I tried serveral works on github but they all failed to perform well.@99991

**Comment by 99991** [comment]
You could try

* information flow matting https://github.com/yaksoy/AffinityBasedMattingToolbox
* shared matting https://www.inf.ufrgs.br/~eslgastal/SharedMatting/#Downloads
* GCA Matting https://github.com/Yaoyi-Li/GCA-Matting

**Comment by lfxx** [comment]
> You could try
> 
> * information flow matting https://github.com/yaksoy/AffinityBasedMattingToolbox
> * shared matting https://www.inf.ufrgs.br/~eslgastal/SharedMatting/#Downloads
> * GCA Matting https://github.com/Yaoyi-Li/GCA-Matting

Ok,i will try it.Thanks for your rapidly reply:)
