### ISSUE TITLE
Cost too much time to compute result

### ISSUE THREAD

**Issue by lfxx** [pymatting/pymatting#11]
When i input a 1280x720 image,use cpu can consume almost 40s to get the result.Any method to use GPU to compute the final result?@99991

**Comment by lfxx** [comment]
When i run your code,get the following warning:
PERFORMANCE WARNING:
Thresholded incomplete Cholesky decomposition failed due to insufficient positive-definiteness of matrix A with parameters:
    discard_threshold = 1.000000e-04
    shift = 0.000000e+00
Try decreasing discard_threshold or start with a larger shift
What should i do to accelerate compute speed?Hope for your kindly reply@99991

**Comment by 99991** [comment]
There are basically three steps to the alpha matting methods implemented in this repository.

1. Compute a matting Laplacian matrix (fast)
2. Compute a preconditioner (slow)
3. Solve a linear system based on the Laplacian matrix using conjugate gradient descent (extremely slow, but reasonably fast with the right preconditioner)

The incomplete Cholesky preconditioner works very well to accelerate the third step, but takes quite a while to compute and is very hard to parallelize, so a GPU would not help much in this case.

Another class of preconditioners which work well for this problem are multigrid preconditioners. One implementation is the AMGCL library, which even has python bindings.

```Python3
import numpy as np
import pyamgcl as amg
import scipy.sparse
from pymatting import *

scale = 1.0

image = load_image("lemur.png", "RGB", scale, "box")
trimap = load_image("lemur_trimap.png", "GRAY", scale, "nearest")

h, w = trimap.shape[:2]

L = cf_laplacian(image)

is_fg, is_bg, is_known, is_unknown = trimap_split(trimap)

lambda_value = 100.0

c = lambda_value * is_known
C = scipy.sparse.diags(c)

b = lambda_value * is_fg

A = L + C

solve = amg.solver(amg.amgcl(A))

x = solve(b)

alpha = np.clip(x, 0.0, 1.0).reshape(h, w)

save_image("lemur_alpha.png", alpha)
```

However, the python bindings don't seem to use the GPU backend by default. Also you might run into floating point issues when using 32 bit floats on the GPU if you should get it to work somehow or use the C++ interface.


The warning from the incomplete Cholesky decomposition is often due to the trimap not being very good. Making a tighter trimap could help and will also make the algorithm run faster. If that fails, you can try to change the `discard_threshold` and `shift` parameters in the call to `ichol`. Note that you might have to use the [expert level interface](https://github.com/pymatting/pymatting/blob/master/examples/expert_example.py).
