### ISSUE TITLE
Thresholded incomplete Cholesky decomposition failed

### ISSUE THREAD

**Issue by koshygeoji** [pymatting/pymatting#19]
When a running with a 8k file and trimap it shows ..

Thresholded incomplete Cholesky decomposition failed due to insufficient positive-definiteness of matrix A with parameters:
    discard_threshold = 1.000000e-04
    shift = 1.000000e-04
Try decreasing discard_threshold or start with a larger shift

and

Thresholded incomplete Cholesky decomposition failed because more than max_nnz non-zero elements were created. Try increasing max_nnz or discard_threshold.

Also please tell me out of these which is the method with best accuracy..

**Comment by 99991** [comment]
Your image is very large. You have these options:

* Use a smaller image.
* Split up the image into (preferably overlapping) tiles, compute the alpha for each tile and then merge the results.
* Get a computer with a lot of memory and increase `max_nnz`, which controls how large the Cholesky decomposition matrix is allowed to get. This matrix is necessary to compute the result in a reasonable amount of time. You can see an example usage of the [`ichol` function](https://github.com/pymatting/pymatting/blob/0e27ed5b7afd427700aaebe68c706ce5e0034231/pymatting/preconditioner/ichol.py#L153) which has the optional `max_nnz` parameter in the [expert example](https://github.com/pymatting/pymatting/blob/master/examples/expert_example.py).
* Use the `jacobi` preconditioner instead of the `ichol` preconditioner in the [expert example](https://github.com/pymatting/pymatting/blob/0e27ed5b7afd427700aaebe68c706ce5e0034231/examples/expert_example.py#L35), i.e. `M = jacobi(A)` instead of `M = ichol(A)` and wait a long time. This is going to be very boring, so you can add a callback to the `cg` method to display the intermediate alpha for entertainment:
```python
# Run in the pymatting/examples/-directory
from pymatting import *
import numpy as np
import scipy.sparse

scale = 1.0

image = load_image("../data/lemur/lemur.png", "RGB", scale, "box")
trimap = load_image("../data/lemur/lemur_trimap.png", "GRAY", scale, "nearest")

# height and width of trimap
h, w = trimap.shape[:2]

# calculate laplacian matrix
L = cf_laplacian(image)

# decompose trimap
is_fg, is_bg, is_known, is_unknown = trimap_split(trimap)

# constraint weight
lambda_value = 100.0

# build constraint pixel selection matrix
c = lambda_value * is_known
C = scipy.sparse.diags(c)

# build constraint value vector
b = lambda_value * is_fg

# build linear system
A = L + C

# build ichol preconditioner for faster convergence
M = jacobi(A)

# solve linear system with conjugate gradient descent

class ImageViewerCallback(object):
    def __init__(self):
        self.n = 0

    def __call__(self, A, x, b, norm_b, r, norm_r):
        self.n += 1

        print("iteration %7d - %e (%.20f)" % (self.n, norm_r, norm_r))

        alpha = np.clip(x, 0.0, 1.0).reshape(h, w)

        import cv2
        cv2.imshow("image", alpha)
        cv2.waitKey(1)

x = cg(A, b, M=M, callback=ImageViewerCallback())

# clip and reshape result vector
alpha = np.clip(x, 0.0, 1.0).reshape(h, w)

save_image("lemur_alpha.png", alpha)

```
* Try the [pyamg preconditioner](https://github.com/pyamg/pyamg) (might run out of memory).
```
import pyamg
M = pyamg.smoothed_aggregation_solver(A).aspreconditioner()
```
