### ISSUE TITLE
Questions about parameters during testing

### ISSUE THREAD

**Issue by CruiseShao** [pymatting/pymatting#20]
I'm using the sample code provided in the documentation for testing, but the final keying effect is not good, what parameters should I adjust to improve the result?
![lemur_grid](https://user-images.githubusercontent.com/38639098/85366673-6c7c7000-b55a-11ea-9e1e-d0930997abb8.png)

**Comment by 99991** [comment]
This is a very hard image because of the strong JPEG artifacts, reflections and regions with very similar foreground and background colors or large color variations. However, you can still get slightly better results by drawing a better trimap where the white region only touches the car, but not the background. In addition, using a larger value for the `epsilon` parameter helps when using the closed form matting laplacian:

![grid](https://user-images.githubusercontent.com/18725165/85431130-651c8d00-b581-11ea-830b-30601a38bd05.png)

```python
from pymatting import *
import numpy as np

scale = 1.0

image = load_image("image.png", "RGB", scale, "box")
trimap = load_image("trimap.png", "GRAY", scale, "nearest")

# estimate alpha from image and trimap
alpha = estimate_alpha_cf(image, trimap, laplacian_kwargs=dict(epsilon=1e-4))

# make gray background
new_background = np.zeros(image.shape)
new_background[:, :] = [0.5, 0.5, 0.5]

# estimate foreground from image and alpha
foreground, background = estimate_foreground_ml(image, alpha, return_background=True)

# blend foreground with background and alpha, less color bleeding
new_image = blend(foreground, new_background, alpha)

# save results in a grid
images = [image, trimap, alpha, new_image]
grid = make_grid(images)
save_image("grid.png", grid)

# save alpha
save_image("alpha.png", alpha)

# save foreground
save_image("foreground.png", foreground)

# save background
save_image("background.png", background)

# save cutout
cutout = stack_images(foreground, alpha)
save_image("cutout.png", cutout)
```

Alternatively, you could try the knn laplacian with few neighbors and relatively strong distance weights.

![grid](https://user-images.githubusercontent.com/18725165/85432760-b4fc5380-b583-11ea-8225-dc3d9b70fb78.png)

```python
alpha = estimate_alpha_knn(image, trimap, laplacian_kwargs=dict(
    n_neighbors=[5],
    distance_weights=[100.0]))
```

But the shape of the car is relatively simple, so it might be easier to simply trace the outline and apply some antialiasing.

**Comment by CruiseShao** [comment]
Thank you very much for your reply and I will try your method.

**Comment by CruiseShao** [comment]
> Thank you very much for your reply and I will try your method.

**Comment by CruiseShao** [comment]
> Thank you very much for your reply and I will try your method.

Thank you very much for your reply and I will try your method.
