### ISSUE TITLE
pixelated edges?

### ISSUE THREAD

**Issue by ucb-pb** [pymatting/pymatting#21]
Wondering why the results are so poor from images like this.  Any tips/ideas?

Original:

![00016](https://user-images.githubusercontent.com/56403009/85449679-0c8bc680-b566-11ea-932c-70bbd8bbfeef.jpg)

Trimap:

![00016](https://user-images.githubusercontent.com/56403009/85449778-23321d80-b566-11ea-8db2-5098ff0551bf.png)

The cutout:

![00016](https://user-images.githubusercontent.com/56403009/85449586-efef8e80-b565-11ea-8e73-7336ef30b53f.png)

**Comment by 99991** [comment]
The block artifacts are from the input image due to JPEG compression. You can reduce the effect slightly by increasing the value of the epsilon parameter of the closed form matting Laplacian in the [advanced example](https://github.com/pymatting/pymatting/blob/0e27ed5b7afd427700aaebe68c706ce5e0034231/examples/advanced_example.py#L10) but this will destroy fine details.

![grid](https://user-images.githubusercontent.com/18725165/85455042-d407df00-b59d-11ea-9980-fbbf9f08b1df.png)

```python
alpha = estimate_alpha_cf(image, trimap, laplacian_kwargs=dict(epsilon=1e-5))
```

There also exist tools to undo the damage done by JPEG compression, but it would be best to work with uncompressed images instead. Sometimes it also helps to simply blur the input image a bit.

**Comment by ucb-pb** [comment]
Thank you very much.
