### ISSUE TITLE
ValueError on import

### ISSUE THREAD

**Issue by Mathux** [pymatting/pymatting#3]
Hi,
I installed the lib but there are a problem with the importation of your package.

I am using python 3.8.1 with :
numpy=1.18.1 (>=1.16.0)
pillow=6.2.1 (>=5.2.0)
numba=0.47.0 (>=0.44.0)
scipy=1.3.3 (>=1.1.0)

*** ValueError: Failed in nopython mode pipeline (step: convert to parfors)
Cannot add edge as dest node 26 not in nodes {130, 132, 262, 264, 528, 30, 418, 302, 564, 565, 566, 568, 322, 450, 196, 452, 324, 340, 212, 86, 214, 348, 94, 228, 356, 494, 118, 246, 248, 378, 380}

(you can read all here: https://gyazo.com/b6b9756f0c8d75a30a63dada09c5f82e)

Thank you for your work :+1:

**Comment by 99991** [comment]
Thank you for your bug report! :tada:

I just upgraded to your numba and numpy versions, but unfortunately I can not reproduce this bug. It seems to be numba-related though, which is why we might have to forward this issue to the numba issue tracker.

Nevertheless, we can still try to narrow it down a bit. I think the bug might be related to how numba parallelization works. Maybe the error goes away when disabling it.

Could you try replacing the four occurences ([1](https://github.com/pymatting/pymatting/blob/a1aec314a07beb5771222222f3bb83e6121f3058/pymatting/util/kdtree.py), [2, 3, 4](https://github.com/pymatting/pymatting/blob/a1aec314a07beb5771222222f3bb83e6121f3058/pymatting/util/boxfilter.py)) of `parallel=True` with `parallel=False`, for example by running
```bash
find -name '*.py' -exec sed -i 's/parallel=True/parallel=False/g' {} +
pip install .
```
in the pymatting directory?

If that does not work, we could try the same with replacing `prange` with `range`:

```bash
find -name '*.py' -exec sed -i 's/prange(/range(/g' {} +
pip install .
```

Lastly, do you have any idea what else might be different between our installs? I've tried Ubuntu 16.04 and 18.04 (see version with `lsb_release -a`), but no bugs so far.

**Comment by Mathux** [comment]
Thank you for your quick response :)

You are right, when I changed the four occurrences of ``parallel=True`` with ``parallel=False``, the problem disappeared and I can now import and use your library.

With this change, I passed 9/10 tests. (The last one failed because I don't have the ``cupy`` package: 
``ModuleNotFoundError: No module named 'cupy'`` which doesn't seem to be a real issue)

I tried on the lemur image with its trimap, and it work nicely.

I am running Arch Linux (which is a rolling distribution).
I tried with another computer on Ubuntu 18.04 and it worked with any bugs.

**Comment by 99991** [comment]
> You are right, when I changed the four occurrences of parallel=True with parallel=False, the problem disappeared and I can now import and use your library.

That's good to hear. We might end up removing parallelism until numba is more stable.

I'll try to reproduce the issue on Arch.

> With this change, I passed 9/10 tests. (The last one failed because I don't have the `cupy` package:
> `ModuleNotFoundError: No module named 'cupy'` which doesn't seem to be a real issue)

That's alright, you just won't be able to use GPU-accelerated foreground estimation methods. New tests with more verbose output about this issue are being worked on.

**Comment by 99991** [comment]
Numba parallel can now be turned on or off in `pymatting/config/config.py`.
