### ISSUE TITLE
[Question❓] How to generate trimaps from u2net output?

### ISSUE THREAD

**Issue by danielgatis** [pymatting/pymatting#33]
Hi @99991,

I am using the [pymatting](https://github.com/pymatting/pymatting) in my lib. Basically, I use the output of [u2net](https://github.com/NathanUA/U-2-Net) and chains in pymatting. 

I generate the trimap based on foreground and background threshold followed by an erosion:
https://github.com/danielgatis/rembg/blob/master/src/rembg/bg.py#L16

I have an issue asking about the optimal values for thresholds and erosion size:
https://github.com/danielgatis/rembg/issues/14#issuecomment-716797225

Is there any technique to generate an optimal trimap based on u2net output?

thanks.

**Comment by 99991** [comment]
It would probably be easiest to train a neural network end-to-end to create the alpha matte directly (instead of some approximate segmentation as U^2-Net is doing), see for example https://wukaoliu.github.io/HAttMatting/

Alternatively, it might be possible to guess how large the dilation/erosion radius has to be based on how "fuzzy" the predicted segmentation by U^2-Net is. Not sure how to measure that though. Maybe fitting some simple model to a downsampled alpha matte is sufficient for your application. Might also be a much harder problem, I have not tried it yet.
It might be a good idea to use distance fields for dilation/erosion, since that method can be computationally faster for large radii (see https://github.com/poppinace/indexnet_matting/blob/ddb374a3e0e1ef3042437b7a88785950d6b0fbe1/scripts/hldataset.py#L201 for an example on how to generate a trimap using distance fields). You could also generate trimaps adaptively, i.e. have different radii for different image regions based on how certain you are that some region needs a larger dilation radius.

Either way, you'd probably need a dataset to calibrate your method.

**Comment by 99991** [comment]
@danielgatis I just found out about https://github.com/JizhiziLi/animal-matting which is mostly focused on animal images, but it also seems to work well for some other object classes. Maybe this is of interest to you.
