### ISSUE TITLE
pytest Error: tests/test_lkm.py:81: AssertionError

### ISSUE THREAD

**Issue by 3dsf** [pymatting/pymatting#4]
**=== warnings summary ===**
> tests/test_foreground.py::test_foreground
>   /home/ferg/git/pymatting/tests/test_foreground.py:31: UserWarning: Tests for GPU implementation skipped, because of missing packages.

I'm on Fedora 31 and here are my pip 3 package versions which above the required dependencies.

> Requirement already satisfied: numpy in /usr/lib64/python3.7/site-packages (1.17.4)
> Requirement already satisfied: pillow in /usr/lib64/python3.7/site-packages (6.1.0)
> Requirement already satisfied: numba in /home/ferg/.local/lib/python3.7/site-packages (0.48.0)
> Requirement already satisfied: scipy in /home/ferg/.local/lib/python3.7/site-packages (1.4.1)

**Comment by 3dsf** [comment]
Not on a nvidia gpu; is this the issue?

**Comment by 99991** [comment]
The warning is because no NVIDIA GPU is available, but that is only required for [GPU-accelerated foreground estimation with CUDA](https://github.com/pymatting/pymatting/blob/master/pymatting/foreground/estimate_foreground_ml_cupy.py#L103). You can still use [the CPU-implementation](https://github.com/pymatting/pymatting/blob/1c08878acd8f309157af40b8e899c5e1d94c9f1b/pymatting/foreground/estimate_foreground_ml.py#L157). And if you are lucky and can install pyopencl, you can also use the [GPU-accelerated OpenCL implementation](https://github.com/pymatting/pymatting/blob/1c08878acd8f309157af40b8e899c5e1d94c9f1b/pymatting/foreground/estimate_foreground_ml_pyopencl.py#L103).

However, the assertion is unrelated to that.

Could you try upgrading numpy and see if the assertion error in `test_lkm` persists?

```
pip install numpy --upgrade
```

If that should not fix it, could you print the `difference` value in [line 81 of tests/test_lkm.py](https://github.com/pymatting/pymatting/blob/1c08878acd8f309157af40b8e899c5e1d94c9f1b/tests/test_lkm.py#L81)?

**Comment by liyiying233** [comment]
There are some problems at runtime in ubuntu16.04
`================================================================================ test session starts =================================================================================
platform linux -- Python 3.6.4, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /home/liyiying/liyiying/git-project/pymatting
collected 11 items                                                                                                                                                                   

tests/test_boxfilter.py .                                                                                                                                                      [  9%]
tests/test_cg.py .                                                                                                                                                             [ 18%]
tests/test_estimate_alpha.py .                                                                                                                                                 [ 27%]
tests/test_foreground.py .                                                                                                                                                     [ 36%]
tests/test_ichol.py .                                                                                                                                                          [ 45%]
tests/test_kdtree.py .                                                                                                                                                         [ 54%]
tests/test_laplacians.py .                                                                                                                                                     [ 63%]
tests/test_lkm.py F                                                                                                                                                            [ 72%]
tests/test_preconditioners.py .                                                                                                                                                [ 81%]
tests/test_simple_api.py .                                                                                                                                                     [ 90%]
tests/test_util.py .                                                                                                                                                           [100%]

`

`>       assert difference < 1e-5
E       assert 5.6514436094818936e-05 < 1e-05

tests/test_lkm.py:56: AssertionError
`

**Comment by 99991** [comment]
We have recently increased the threshold by a small amount. Do the tests pass now?

**Comment by 99991** [comment]
Since there have not been any comments, I'll assume that this issue has been solved.
