### ISSUE TITLE
How to get hand-drawn trimap?

### ISSUE THREAD

**Issue by yangjian1218** [pymatting/pymatting#40]
the inputs of the Net  are input image and a hand-drawn trimap,but ofen we don't have hand-drawn trimap. is there code to make it ? 
_cutout(
    # input image path
    "data/lemur/lemur.png",
    # input trimap path
    "data/lemur/lemur_trimap.png",
    # output cutout path
    "lemur_cutout.png")_

**Comment by 99991** [comment]
Currently, this repository does not contain any code to generate trimaps automatically. The reason is that a photo may contain multiple different objects. Only the user knows which of those objects should be extracted.

If you want to extract a _specific_ kind of object from an image, you could train a neural network to generate the trimap, or even the alpha matte, directly.

For example, if you want to have alpha mattes of animals, there is: https://github.com/JizhiziLi/animal-matting

Alternatively, you could use an existing network for object segmentation and generate a trimap from it with dilation operations, see for example this issue: https://github.com/pymatting/pymatting/issues/33

**Comment by 99991** [comment]
Closed due to inactivity. If you have further questions, feel free to re-open.
