### ISSUE TITLE
Include a MANIFEST.in file

### ISSUE THREAD

**Issue by thewchan** [pymatting/pymatting#50]
I'm attempting to get this package into a binary format on conda-forge; would it be possible to include a MANIFEST.in file? Currently some of the required files are not included in the sdist (e.g. requirement.txt)

https://packaging.python.org/guides/using-manifest-in/

**Comment by 99991** [comment]
We are considering switching back to JIT compilation from AOT compilation since the later causes several issues on Windows and the progress of Numba on that side has not been as fast as I had hoped.

I do not have time to work on this during the next few months, but if anyone wants to write a PR, it should probably include some tests to check if the JIT-to-AOT-switch did not horribly break anything.

**Comment by thewchan** [comment]
Thanks, I'll await for this to be completed before trying again.

**Comment by tuelwer** [comment]
MANIFEST.in file has been merged (pull request #59).
