### ISSUE TITLE
Hello, the images are not included directly for licensing reasons, and if the buttons are like in the picture, it does not violate licensing. [Question❓]

### ISSUE THREAD

**Issue by egoorr** [pymatting/pymatting#71]
![95da313e-4978-4304-a66e-b8f92ad770f6_cleanup](https://github.com/pymatting/pymatting/assets/142255641/419bed4d-f303-48f7-950e-e05b310686e9)

**Comment by 99991** [comment]
I do not understand your question.

1. PyMatting uses images form http://alphamatting.com/datasets.php for testing if PyMatting works correctly. We can not include those images directly in this GitHub repository because the person currently in charge of http://alphamatting.com does not allow it.
2. You posted a photo of the website https://clipdrop.co/remove-background which offers a background removal service. People can upload their own photos from their computers to this website, but I do not see how this website is related to PyMatting.

Could you clearly state what your question is?

**Comment by 99991** [comment]
Closed by https://github.com/pymatting/pymatting/pull/89 (Maybe. OP did not add more details.)
